apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-wds-depl
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.wds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.wds.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.wds.name }}-container
          image: {{ .Values.wds.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "200m"
          volumeMounts:
            - name: {{ include "app.fullname" . }}-wds-config
              mountPath: {{ .Values.wds.conf_dir }}/{{ .Values.wds.conf_file }}
              subPath: {{ .Values.wds.conf_file }}
          env:
            - name: SPRING_CONFIG_ADDITIONAL-LOCATION
              value: {{ .Values.wds.conf_dir }}/{{ .Values.wds.conf_file }}
            - name: WDS_DB_HOST
            value: {{ include "app.fullname" . }}-postgres
            - name: WDS_DB_PASSWORD
            value: {{ include "dbPassword" . | b64enc | quote }}
            - name: WDS_DB_USER
              value: {{ .Values.postgres.user }}
            - name: WDS_DB_NAME
              value: {{ .Values.postgres.wds.dbname }}
            - name: WDS_DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: SWAGGER_BASE_PATH
              value: "{{ .Values.env.swaggerBasePath }}"
            - name: WORKSPACE_ID
              value: "{{ .Values.persistence.workspaceManager.workspaceId }}"
            - name: SAM_URL
              value: "{{ .Values.sam.url }}"
            - name: LZ_MRG
              value: "{{ .Values.config.resourceGroup }}"
            - name: RELEASE_NAME
              value: {{ include "app.fullname" . }}

      volumes:
        - name: {{ include "app.fullname" . }}-wds-config
          configMap:
            name: {{ include "app.fullname" . }}-wds-config
            items:
                - key: {{ .Values.wds.conf_file }}
                  path: {{ .Values.wds.conf_file }}