apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-postgres-startup
data:
  {{ .Values.postgres.startup_scripts.create_dbs }}: |-
      #!/bin/bash
      set -e
      set -u
      
      function create_user_and_database() {
        local database=$1
        echo "  Creating user and database '$database'"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE USER $database;
        CREATE DATABASE $database;
        GRANT ALL PRIVILEGES ON DATABASE $database TO $database;
      EOSQL
      }

      create_user_and_database wds
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-postgres-pvc
        - name: {{ include "app.fullname" . }}-postgres-startup
          configMap:
            name: {{ include "app.fullname" . }}-postgres-startup
            items:
                - key: {{ .Values.postgres.startup_scripts.create_dbs }}
                  path: {{ .Values.postgres.startup_scripts.create_dbs }}
      containers:
        - name: postgres-container
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: {{ include "app.fullname" . }}-postgres-startup
              mountPath: {{ .Values.postgres.startup_dir }}/{{ .Values.postgres.startup_scripts.create_dbs }}
              subPath: {{ .Values.postgres.startup_scripts.create_dbs }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ include "dbPassword" . | b64enc | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}