apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-reverse-proxy-deploy
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ include "app.fullname" . }}-reverse-proxy-config
          configMap:
            name: {{ include "app.fullname" . }}-reverse-proxy-config
            items:
              - key: {{ .Values.proxy.conf_file }}
                path: {{ .Values.proxy.conf_file }}
              - key: {{ .Values.proxy.www_file }}
                path: {{ .Values.proxy.www_file }}
      containers:
        - name: reverse-proxy-container
          image: {{ .Values.proxy.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: {{ include "app.fullname" . }}-reverse-proxy-config
              mountPath: {{ .Values.proxy.conf_dir }}/{{ .Values.proxy.conf_file }}
              subPath: {{ .Values.proxy.conf_file }}
            - name: {{ include "app.fullname" . }}-reverse-proxy-config
              mountPath: {{ .Values.proxy.www_dir }}/{{ .Values.proxy.www_file }}
              subPath: {{ .Values.proxy.www_file }}

          command: ["nginx"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-reverse-proxy-service
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.type }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.proxy.port }}
      targetPort: {{ .Values.proxy.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-reverse-proxy-config
data:
  {{ .Values.proxy.conf_file }}: |-
    daemon off;

    events {
      worker_connections 1024;
    }
    http {
      server {
        access_log /dev/stdout combined;
        listen 8000;

        # Reference to nginx's local content
        location /index.html {
          alias /www/data/index.html;
        }

        location /wds/ {
          client_max_body_size 500m;
          proxy_pass http://{{ include "app.fullname" . }}-wds-svc:8080/;
        }
      }
    }
  {{ .Values.proxy.www_file }}: |-
    <!doctype html>
    <html>
      <head>
        <title>Hello nginx</title>
        <meta charset="utf-8" />
      </head>
      <body>
        <h1>
          WDS as an App on Azure Proxy.
        </h1>
        <p> This is the WDS as an App on Azure proxy. Valid internal paths:</p>
        <ul>
          <li> WDS: <a href="./wds/"> wds/ </a> </li>
          <ul>
            <li> eg: <a href="./wds/swagger/swagger-ui.html"> WDS Swagger </a> </li>
          </ul>
        </ul>
      </body>
    </html>
