apiVersion: v1
kind: Service
metadata:
  name: {{ include "cromwell-local.fullname" . }}
  labels:
    {{- include "cromwell-local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.cromwell.type }}
  ports:
    - port: {{ .Values.service.cromwell.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cromwell-local.selectorLabels" . | nindent 4 }}
