###########################
# External Service for API and Swagger
###########################
apiVersion: v1
kind: Service
metadata:
  name: cromwell-service
spec:
  type: {{ .Values.service.type }}
  selector:
    component: cromwell
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
