###########################
# Deployment
###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-depl
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: broadinstitute/cromwell:68-8e12ab5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command:
            - "bin/bash"
            - "-c"
            - >-
             java
             -jar /app/cromwell.jar
             server
