apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-postgres-pvc
  creationTimestamp: null
  labels:
    io.kompose.service: {{ include "app.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.postgresPvcSize }}
status: {}
