apiVersion: v1
entries:
  Cromwell with Postgres:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-29T16:37:08.323559-04:00"
    description: Simple Cromwell deployment with Postgres database
    digest: dcb4a05c3517b1b8fab34c79444bf57fc876c398e0573f1562352d5ea1ddd823
    name: Cromwell with Postgres
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/Cromwell-With-Postgres-0.1.0.tgz
    version: 0.1.0
  CromwellHsqldbLocalMinikube:
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.325778-04:00"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 3dd85df71a65c04306a195df27f066dc67f7a46e5b271ead0759c1819323f54a
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.325135-04:00"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: a4b97391c01fc03322d82605c47b887b37a1254cfbbf22bf47ab8d31d3114831
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.324278-04:00"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 68d53f23cea57a45c49ec37a2b22a54d8ca937ed5271501676f86ddf86f693f2
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.0.tgz
    version: 0.1.0
  cromwell:
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.32811-04:00"
    description: Simple Cromwell deployment with Postgres database running jobs locally
    digest: cf318a0ac13836eb71312058f512e8e9f92e58a4cbb061f41c09e770eb42dfbb
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.327524-04:00"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 072eb6464b8ae6f2744adef995b1a7807ff3e9879db80557f0904b703a494144
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2021-10-29T16:37:08.32663-04:00"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 56c38a6b51039fe0ffa458db073272a616d3f3ae0fdf7eb8fb9079ee17604122
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.3.tgz
    version: 0.1.3
  cromwellwithpostgress:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-29T16:37:08.329601-04:00"
    description: Simple Cromwell deployment with Postgres database
    digest: ad93460102e6d790e3255981b1dc151b36ef578064eaff7950186cd6258f8a37
    name: cromwellwithpostgress
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwellwithpostgress-0.1.0.tgz
    version: 0.1.0
  pgcromwell:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-29T16:37:08.330689-04:00"
    description: Simple Cromwell deployment with Postgres database
    digest: 52c9420bed5f821d2407a67f8f9e74635e72fccdf3e17c5290190c8ed1b55bba
    name: pgcromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/pgcromwell-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-29T16:37:08.322587-04:00"
