apiVersion: v1
entries:
  Cromwell with Postgres:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-25T14:44:20.902373871Z"
    description: Simple Cromwell deployment with Postgres database
    digest: dcb4a05c3517b1b8fab34c79444bf57fc876c398e0573f1562352d5ea1ddd823
    name: Cromwell with Postgres
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/Cromwell-With-Postgres-0.1.0.tgz
    version: 0.1.0
  CromwellHsqldbLocalMinikube:
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.903206781Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 3dd85df71a65c04306a195df27f066dc67f7a46e5b271ead0759c1819323f54a
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.902898377Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: a4b97391c01fc03322d82605c47b887b37a1254cfbbf22bf47ab8d31d3114831
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.902583773Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 68d53f23cea57a45c49ec37a2b22a54d8ca937ed5271501676f86ddf86f693f2
    name: CromwellHsqldbLocalMinikube
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/CromwellHsqldbLocalMinikube-0.1.0.tgz
    version: 0.1.0
  cromwell:
  - apiVersion: v2
    appVersion: 79-7af4ecf-SNAP
    created: "2022-04-25T14:44:20.907223632Z"
    description: Simple Cromwell deployment with Postgres database with Local and
      PAPIv2 (application-default) backends configured.
    digest: d7b5267791ac8bfa0f7c0d67f7223de0714619f435ec4d82a6f9b95999383eb7
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 71-c778c33
    created: "2022-04-25T14:44:20.903721988Z"
    description: Simple Cromwell deployment with Postgres database with Local and
      PAPIv2 (application-default) backends configured.
    digest: c2f977edbf7d89a5bf2fbf4ec73f3bbf2891f89ff0a8702892870559ec7f5eb2
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 71-c778c33
    created: "2022-04-25T14:44:20.906492422Z"
    description: Simple Cromwell deployment with Postgres database with Local and
      PAPIv2 (application-default) backends configured.
    digest: 109d47515f35689e3b778780f37574855895e8bca72f3b5dacf24923898119ea
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 71-c778c33
    created: "2022-04-25T14:44:20.906042017Z"
    description: Simple Cromwell deployment with Postgres database with Local and
      PAPIv2 (application-default) backends configured.
    digest: 810251c2557c8fae747ed3c2edec01a42ea9d63eb5ebb9b62cdba81cb067bf97
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 71-c778c33
    created: "2022-04-25T14:44:20.905609311Z"
    description: Simple Cromwell deployment with Postgres database running jobs locally
    digest: e9b28fac462f69f48c89bc28d8d168cd3dcdbdab5b8243d0d09e6129fbfe7fd4
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.905239807Z"
    description: Simple Cromwell deployment with Postgres database running jobs locally
    digest: ae59ae9fa9765891d8e15f1e477901a55cbd1346621d7b7029298323c5f5fbf5
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.904825501Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: cf318a0ac13836eb71312058f512e8e9f92e58a4cbb061f41c09e770eb42dfbb
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.904415296Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 072eb6464b8ae6f2744adef995b1a7807ff3e9879db80557f0904b703a494144
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 68-8e12ab5
    created: "2022-04-25T14:44:20.904046992Z"
    description: Simple Cromwell deployment with in-memory database running jobs locally
    digest: 56c38a6b51039fe0ffa458db073272a616d3f3ae0fdf7eb8fb9079ee17604122
    name: cromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/cromwell-0.1.3.tgz
    version: 0.1.3
  pgcromwell:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-25T14:44:20.907578736Z"
    description: Simple Cromwell deployment with Postgres database
    digest: 52c9420bed5f821d2407a67f8f9e74635e72fccdf3e17c5290190c8ed1b55bba
    name: pgcromwell
    type: application
    urls:
    - https://broadinstitute.github.io/cromwhelm/charts/pgcromwell-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-25T14:44:20.900807951Z"
