apiVersion: v2
name: cromwell
description: Simple Cromwell deployment with Postgres database with Local and PAPIv2 (application-default) backends configured.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.176

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

# Keep this format stable for automatic version bumps from https://github.com/broadinstitute/cromwell/pull/6739
appVersion: "85-dce3fe7"

dependencies:
  - name: terra-batch-libchart
    version: 0.0.2
    repository: file://../terra-batch-libchart
    import-values:
      - common
