config:
  gcsBucket: "SUPPLIED BY LEO"
  gcsProject: "SUPPLIED BY LEO"
  gcsRegion: us-central1 # TODO: SUPPLY VIA LEO (BW-924)
  papiv2EndpointUrl: https://lifesciences.googleapis.com/ # TODO: SUPPLY VIA LEO... or hard-code into Cromwell? (BW-924)
  serviceAccount:
    name: "SUPPLIED BY LEO"
    annotations:
      gcpServiceAccount: "SUPPLIED BY LEO"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/rewrite-target: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/auth-tls-secret: "SUPPLIED BY LEO"
  path: "SUPPLIED BY LEO"
  hosts:
    - host: "SUPPLIED BY LEO"
      paths:
        - "SUPPLIED BY LEO"
  tls:
    - secretName: "SUPPLIED BY LEO"
      hosts:
        - "SUPPLIED BY LEO"

persistence:
  enabled: true
  storageClass: "manual"
  size: 10G
  accessMode: ReadWriteOnce
  mountPath: "/data"
  gcePersistentDisk: "SUPPLIED BY LEO"

postgres:
  password: "SUPPLIED BY LEO"

cromwell:
  name: cromwell-api
  config:
    dir: /etc/conf
    file: papi.conf

cbas:
  enabled: false

identity:
  clientId: RUNTIME_PARAMETER

autopilot:
  enabled: false
  app:
