service:
  type: ClusterIP
  port: 8000

cromwellConfig:
  configDir: /etc/conf
  configFile: papi.conf
  gcsBucket: gs://cromwell_k8s_papi/cromwell-execution # TODO: SUPPLY VIA LEO
  gcsProject: broad-dsde-cromwell-dev # TODO: SUPPLY VIA LEO

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/rewrite-target: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/auth-tls-secret: "SUPPLIED BY LEO"
  path: "SUPPLIED BY LEO"
  hosts:
    - host: "SUPPLIED BY LEO"
      paths:
        - "SUPPLIED BY LEO"
  tls:
    - secretName: "SUPPLIED BY LEO"
      hosts:
        - "SUPPLIED BY LEO"

persistence:
  enabled: true
  storageClass: "manual"
  size: 10G
  accessMode: ReadOnlyMany
  mountPath: "/data"
  gcePersistentDisk: "SUPPLIED BY LEO"

db:
  name: cromwell
  port: 5432
  user: postgres_user
  password: "SUPPLIED BY LEO"

env:
  swaggerBasePath: "SUPPLIED BY LEO"
