service:
  type: ClusterIP
  port: 8000

config:
  dir: /etc/conf
  file: papi.conf
  gcsBucket: "SUPPLIED BY LEO"
  gcsProject: "SUPPLIED BY LEO"
  gcsRegion: us-central1 # TODO: SUPPLY VIA LEO (BW-924)
  papiv2EndpointUrl: https://lifesciences.googleapis.com/ # TODO: SUPPLY VIA LEO... or hard-code into Cromwell? (BW-924)
  serviceAccount:
    name: "SUPPLIED BY LEO"
    annotations:
      gcpServiceAccount: "SUPPLIED BY LEO"
  proxy:
    conf_dir: /etc/nginx
    conf_file: nginx.conf
    www_dir: /www/data
    www_file: index.html
  cbas:
    conf_dir: /etc/conf
    conf_file: cbas.yaml
  cbasUI:
    conf_file: config.json
    conf_dir: /usr/share/nginx/html
  wds:
    conf_dir: /etc/conf
    conf_file: wds.yaml
  postgres:
    startup_dir: /docker-entrypoint-initdb.d
    helper_dir: /wds-helpers
    startup_scripts:
      # Numbered because scripts in initdb.d are run in alphabetical order:
      create_dbs: 01_create_dbs.sh
      seed_wds: 02_seed_wds.sql

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/rewrite-target: "SUPPLIED BY LEO"
    nginx.ingress.kubernetes.io/auth-tls-secret: "SUPPLIED BY LEO"
  path: "SUPPLIED BY LEO"
  hosts:
    - host: "SUPPLIED BY LEO"
      paths:
        - "SUPPLIED BY LEO"
  tls:
    - secretName: "SUPPLIED BY LEO"
      hosts:
        - "SUPPLIED BY LEO"

persistence:
  enabled: true
  storageClass: "manual"
  size: 10G
  accessMode: ReadOnlyMany
  mountPath: "/data"
  gcePersistentDisk: "SUPPLIED BY LEO"

db:
  port: 5432
  user: postgres_user
  password: "SUPPLIED BY LEO"
  wds:
    dbname: wds
  cromwell:
    dbname: cromwell

jobmanager:
  name: jobmanager
  applicationVersion: latest
  ui:
    image:
      repository: us.gcr.io/broad-dsp-gcr-public/job-manager-ui
      tag:
    service:
      type: ClusterIP
      port: 8000
    probes:
      readiness:
        # ui.probes.readiness.enable -- Whether to configure a readiness probe
        enabled: true
        # ui.probes.readiness.spec -- Kubernetes spec for readiness probe
        spec:
          httpGet:
            path: /health
            port: 8000
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
      liveness:
        # ui.probes.liveness.enable -- Whether to configure a liveness probe
        enabled: true
        # ui.probes.liveness.spec -- Kubernetes spec for liveness probe
        spec:
          httpGet:
            path: /health
            port: 8000
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
  api:
    image:
      repository: us.gcr.io/broad-dsp-gcr-public/job-manager-api-cromwell
      tag:
    service:
      type: ClusterIP
      port: 8190
    probes:
      TODO: Fix these health checks, which may be more than just not being able to connect to Cromwell
      readiness:
        # api.probes.readiness.enable -- Whether to configure a readiness probe
        enabled: false # TODO: enable after connecting to Cromwell -breilly 20220420
        # api.probes.readiness.spec -- Kubernetes spec for readiness probe
        spec:
          httpGet:
            path: /api/v1/health
            port: 8190
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
      liveness:
        # api.probes.liveness.enable -- Whether to configure a liveness probe
        enabled: false # TODO: enable after connecting to Cromwell -breilly 20220420
        # api.probes.liveness.spec -- Kubernetes spec for liveness probe
        spec:
          httpGet:
            path: /api/v1/health
            port: 8190
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 30 # 5 minutes before restarted
          successThreshold: 1

cromwell:
  name: cromwell-api

cbasUI:
  name: cbas-ui
  image: us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.6

cbas:
  name: cbas
  image: us.gcr.io/broad-dsp-gcr-public/cbas:0.0.18

wds:
  name: wds
  image: gcr.io/broad-dsde-dev/workspacedata

env:
  swaggerBasePath: "SUPPLIED BY LEO"
