# TODO: The values below were copied -- do we need this?
dbname: wds

env:
  swaggerBasePath: "SUPPLIED BY LEO"

identity:
  name: RUNTIME_PARAMETER
  resourceId: RUNTIME_PARAMETER
  clientId: RUNTIME_PARAMETER

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

persistence:
  enabled: true
  storageClass: "manual"
  postgresPvcSize: 10G
  accessMode: ReadWriteOnce # TODO - is this the appropriate accessMode
  mountPath: "/data"
  leoAppInstanceName: RUNTIME_PARAMETER
  workspaceManager:
    workspaceId: RUNTIME_PARAMETER

postgres:
  image: postgres
  port: 5432
  user: postgres_user
  password: "RUNTIME_PARAMETER"
  dbname: wds
  startup_dir: /docker-entrypoint-initdb.d
  startup_scripts: # Numbered because the scripts in initdb.d are run in alphabetical order
    create_dbs: 01_create_dbs.sh

sam:
  url: "UNDEFINED"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  # When running via the helm chart configuration, I had to change this from NodePort to LoadBalancer.
  # Before deploying:
  # 1) minikube addons enable metallb
  # 2) minikube ip
  # 2) minikube addons configure metallb
  #    Specify Load Balancer IP range based on minikube ip, eg. 192.168.49.105 to 192.168.49.120)
  type: LoadBalancer
  port: 8000

wds:
  name: wds
  image: us.gcr.io/broad-dsp-gcr-public/terra-workspace-data-service:fde7e29
  conf_dir: /etc/conf
  conf_file: wds.yaml
  enabled: true