identity:
  name: RUNTIME_PARAMETER

persistence:
  enabled: true
  storageClass: "manual"
  size: 10G
  accessMode: ReadWriteOnce
  mountPath: "/data"
  gcePersistentDisk: "SUPPLIED BY LEO"
  leoAppInstanceName: RUNTIME_PARAMETER
  workspaceManager:
    workspaceId: RUNTIME_PARAMETER

# Minikube IP: http://192.168.49.2/