{{- include "terra-batch-libchart.cbas-api-config" (list . "coa-helm.cbas-api-config") -}}
{{- define "coa-helm.cbas-api-config" -}}
# Overrides go here
data:
  {{ .Values.config.cbas.conf_file }}: |-
    workflow-engines:
      cromwell:
        baseUri: 'http://{{ include "app.fullname" . }}-cromwell-svc:8000'
        healthUri: 'http://{{ include "app.fullname" . }}-cromwell-svc:8000/engine/v1/status'
    terra.common:
      tracing:
        stackdriverExportEnabled: false
{{- end -}}