apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cromwell-tmp-claim
  name: cromwell-tmp-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cromwellTmpSize }}
status: {}

---

{{- $rg  := .Values.persistence.storageResourceGroup -}}
{{- $storageAccount  := .Values.persistence.storageAccount -}}
{{- $size  := .Values.persistence.blobPvcSize -}}
{{- range .Values.containers }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-{{ . }}
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  resourceGroup: {{ $rg }}
  storageAccount: {{ $storageAccount }}
  containerName: {{ . }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ . }}-claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $size }}
  storageClassName: blob-{{ . }}
---
{{- end }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-postgres-pvc
  creationTimestamp: null
  labels:
    io.kompose.service: {{ include "app.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.blobPvcSize }}
status: {}
