{{- if .Values.cromwell.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cromwell-tmp-claim
  name: cromwell-tmp-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cromwellTmpSize }}
status: {}
{{ end }}

---

{{- if or (.Values.postgres.podLocalDatabaseEnabled) (.Values.postgres.podLocalDatabaseEnabledForTES) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-postgres-pvc
  creationTimestamp: null
  labels:
    io.kompose.service: {{ include "app.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.postgresPvcSize }}
status: {}
{{ end }}
