apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: relaylistener
  name: relaylistener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: relaylistener
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: relaylistener
        aadpodidbinding: {{ .Values.identity.name }}
    spec:
      containers:
        - name: relaylistener
          image: {{ .Values.relaylistener.image }}
          ports:
            - containerPort: {{ .Values.relaylistener.port }}
          env:
            - name: LISTENER_RELAYCONNECTIONSTRING
              value: {{ .Values.relaylistener.connectionString }}
            - name: LISTENER_RELAYCONNECTIONNAME
              value: {{ .Values.relaylistener.connectionName }}
            - name: LISTENER_TARGETPROPERTIES_TARGETHOST
              value: {{ .Values.relaylistener.targetHost }}
            - name: LISTENER_TARGETPROPERTIES_REMOVEENTITYPATHFROMHTTPURL
              value: "true"
            - name: LISTENER_REQUESTINSPECTORS
              value: "SAM_CHECKER"
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMURL
              value: {{ .Values.relaylistener.samUrl }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMRESOURCEID
              value: {{ .Values.relaylistener.samResourceId }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMRESOURCETYPE
              value: {{ .Values.relaylistener.samResourceType }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMACTION
              value: {{ .Values.relaylistener.samAction }}
      imagePullSecrets:
        - name: acr-secret
