{{- include "cromwell-common.reverse-proxy-config" (list . "coa-helm.reverse-proxy-config") -}}
{{- define "coa-helm.reverse-proxy-config" -}}
data:
  additionalName: {{ include "app.additionalName" . }}
{{- end -}}