apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-cromwell-svc
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "app.cromwell.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.cromwellPort | quote }}
      port: {{ .Values.service.cromwellPort }}
      targetPort: {{ .Values.service.cromwellPort }}
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tes
  name: tes
spec:
  ports:
    - name: {{ .Values.service.tesPort | quote }}
      port: {{ .Values.service.tesPort }}
      targetPort: {{ .Values.service.tesPort }}
  selector:
    io.kompose.service: tes
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  ports:
    - name: {{ .Values.db.port | quote }}
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    io.kompose.service: mysqldb
status:
  loadBalancer: {}
