=======
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tes
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tes
        aadpodidbinding: {{ .Values.identity.name }}
    spec:
      containers:
        - env:
          # TODO remove unused
            - name: DefaultStorageAccountName
              value: {{ .Values.persistence.storageAccount }}
            - name: AzureServicesAuthConnectionString
              value: {{ .Values.config.azureServicesAuthConnectionString }}
            - name: ApplicationInsightsAccountName
              value: {{ .Values.config.applicationInsightsAccountName }}
            - name: ApplicationInsightsAccountKey
              value: {{ .Values.config.applicationInsightsAccountKey }}
            - name: CosmosDbAccountName
              value: {{ .Values.config.cosmosDbAccountName }}
            - name: AzureOfferDurableId
              value: {{ .Values.config.azureOfferDurableId }}
            - name: BatchAccount__AccountName
              value: {{ .Values.config.batchAccountName }}
            - name: BatchAccount__BaseUrl
              value: "https://{{ .Values.config.batchAccountName }}.{{ .Values.config.region }}.batch.azure.com"
            - name: BatchAccount__AppKey
              value: {{ .Values.config.batchAccountKey }}
            - name: BatchAccount__Region
              value: {{ .Values.config.region }}
            - name: BatchAccount__SubscriptionId
              value: {{ .Values.config.subscriptionId }}
              - name: BatchAccount__ResourceGroup
              value: {{ .Values.config.resourceGroup }}
            - name: BatchNodesSubnetId
              value: {{ .Values.config.batchNodesSubnetId }}
            - name: RetryPolicyOptions__MaxRetryCount
              value: 5
            - name: RetryPolicyOptions__ExponentialBackOffExponent
              value: 2
            - name: ContainerRegistry__AutoDiscoveryEnabled
              value: false
            - name: ContainerRegistry__RegistryInfoCacheExpirationInHour
              value: 1
            - name: Terra__LandingZoneId:
              value: {{ .Values.config.landingZoneId }}
            - name: Terra__LandingZoneApiHost:
              value: {{ .Values.persistence.workspaceManager.url }}
            - name: Terra__WsmApiHost:
              value: {{ .Values.persistence.workspaceManager.url }}
            - name: Terra__WorkspaceStoragecontainerResourceId:  # lower-case c?
              value: {{ .Values.persistence.workspaceManager.containerResourceId }}
            - name: Terra__WorkspaceStorageContainerName:
              value: {{ .Values.persistence.blobContainer }}
            - name: Terra__WorkspaceStorageAccountName:
              value: {{ .Values.persistence.storageAccount }}
            - name: BlobxferImageName
              value: {{ .Values.config.blobxferImageName }}
            - name: DisableBatchNodesPublicIpAddress
              value: {{ .Values.config.disableBatchNodesPublicIpAddress | quote }}
            - name: DisableBatchScheduling
              value: {{ .Values.config.disableBatchScheduling | quote }}
            - name: DockerInDockerImageName
              value: {{ .Values.config.dockerInDockerImageName }}
            - name: UsePreemptibleVmsOnly
              value: {{ .Values.config.usePreemptibleVmsOnly | quote}}
            - name: MarthaUrl
              value: {{ .Values.config.drsUrl }}
            - name: CromwellDrsLocalizerImageName
              value: {{ .Values.cromwell.image | replace "cromwell" "cromwell-drs-localizer" }}
          image: {{ .Values.tes.image }}
          name: tes
          ports:
            - containerPort: {{ .Values.tes.port }}
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tes
  name: tes
spec:
  ports:
    - name: {{ .Values.tes.port | quote }}
      port: {{ .Values.tes.port }}
      targetPort: {{ .Values.tes.port }}
  selector:
    io.kompose.service: tes
status:
  loadBalancer: {}
