apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}-tes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tes
        aadpodidbinding: {{ .Values.identity.name }}
    spec:
      containers:
        - env:
            # Name needs to be unique per LZ with max length 9. coa-ABCDEF-coa-rls -> ABCDEF
            # Caution!! Consider hardening this to ensure uniqueness.
            - name: Name
              value: {{ .Values.fullnameOverride | substr 4 10 }}
            - name: ApplicationInsights_Connection_String
              value: {{ .Values.config.applicationInsightsAccountKey }}
            - name: AzureOfferDurableId
              value: {{ .Values.tes.azureOfferDurableId }}
            - name: BatchAccount__AccountName
              value: {{ .Values.config.batchAccountName }}
            - name: BatchAccount__BaseUrl
              value: "https://{{ .Values.config.batchAccountName }}.{{ .Values.config.region }}.batch.azure.com"
            - name: BatchAccount__AppKey
              value: {{ .Values.config.batchAccountKey }}
            - name: BatchAccount__Region
              value: {{ .Values.config.region }}
            - name: BatchAccount__SubscriptionId
              value: {{ .Values.config.subscriptionId }}
            - name: BatchAccount__ResourceGroup
              value: {{ .Values.config.resourceGroup }}
            # Not currently working
            # - name: BatchNodesSubnetId
            #   value: {{ .Values.config.batchNodesSubnetId }}
            - name: RetryPolicyOptions__MaxRetryCount
              value: {{ .Values.tes.retryPolicyOptions.maxRetryCount | quote }}
            - name: RetryPolicyOptions__ExponentialBackOffExponent
              value: {{ .Values.tes.retryPolicyOptions.exponentialBackOffExponent | quote }}
            - name: ContainerRegistry__AutoDiscoveryEnabled
              value: {{ .Values.tes.containerRegistry.autoDiscoveryEnabled | quote }}
            - name: ContainerRegistry__RegistryInfoCacheExpirationInHour
              value: {{ .Values.tes.containerRegistry.registryInfoCacheExpirationInHour | quote }}
            - name: Terra__LandingZoneId
              value: {{ .Values.config.landingZoneId }}
            - name: Terra__LandingZoneApiHost
              value: {{ .Values.persistence.workspaceManager.url }}
            - name: Terra__SasTokenExpirationInSeconds
              value: {{ .Values.tes.sasTokenExpirationInSeconds | quote }}
            - name: Terra__WsmApiHost
              value: {{ .Values.persistence.workspaceManager.url }}
            - name: Terra__WorkspaceStorageContainerResourceId
              value: {{ .Values.persistence.workspaceManager.containerResourceId }}
            - name: Terra__WorkspaceStorageContainerName
              value: {{ .Values.persistence.blobContainer }}
            - name: Terra__WorkspaceStorageAccountName
              value: {{ .Values.persistence.storageAccount }}
            - name: Terra__WorkspaceId
              value: {{ .Values.persistence.workspaceManager.workspaceId }}
            - name: DisableBatchNodesPublicIpAddress
              value: {{ .Values.tes.disableBatchNodesPublicIpAddress | quote }}
            - name: DisableBatchScheduling
              value: {{ .Values.tes.disableBatchScheduling | quote }}
            - name: DockerInDockerImageName
              value: {{ .Values.tes.dockerInDockerImageName }}
            - name: UsePreemptibleVmsOnly
              value: {{ .Values.tes.usePreemptibleVmsOnly | quote}}
            - name: MarthaUrl
              value: {{ .Values.config.drsUrl }}
            - name: CromwellDrsLocalizerImageName
              value: {{ .Values.cromwell.image | replace "cromwell" "cromwell-drs-localizer" }}
            - name: TesPostgreSql__PostgreSqlServerName
              value: {{ include "app.fullname" . }}
            - name: TesPostgreSql__PostgreSqlServerNameSuffix
              value: "-postgres"
            - name: TesPostgreSql__PostgreSqlServerSslMode
              value: Disable
            - name: TesPostgreSql__PostgreSqlServerPort
              value: {{ .Values.postgres.port | quote }}
            - name: TesPostgreSql__PostgreSqlDatabaseName
              value: {{ .Values.postgres.tes.dbname }}
            - name: TesPostgreSql__PostgreSqlDatabaseUserLogin
              value: {{ .Values.postgres.user | quote }}
            - name: TesPostgreSql__PostgreSqlDatabaseUserPassword
              value: {{ include "dbPassword" . | b64enc | quote }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.tes.logLevel }}
            - name: AllowedHosts
              value: {{ .Values.tes.allowedHosts | quote }}
            - name: BatchImagePublisher
              value: {{ .Values.tes.batchImagePublisher }}
            - name: BatchImageOffer
              value: {{ .Values.tes.batchImageOffer }}
            - name: BatchImageSku
              value: {{ .Values.tes.batchImageSku | quote }}
            - name: BatchImageVersion
              value: {{ .Values.tes.batchImageVersion }}
            - name: BatchNodeAgentSkuId
              value: {{ .Values.tes.batchNodeAgentSkuId }}
            - name: Gen2BatchNodeAgentSkuId
              value: {{ .Values.tes.gen2BatchNodeAgentSkuId }}
            - name: Gen2BatchImageOffer
              value: {{ .Values.tes.gen2BatchImageOffer }}
            - name: Gen2BatchImagePublisher
              value: {{ .Values.tes.gen2BatchImagePublisher }}
            - name: Gen2BatchImageSku
              value: {{ .Values.tes.gen2BatchImageSku | quote }}
            - name: Gen2BatchImageVersion
              value: {{ .Values.tes.gen2BatchImageVersion }}
            - name: Gen1BatchImageOffer
              value: {{ .Values.tes.gen1BatchImageOffer }}
            - name: Gen1BatchImagePublisher
              value: {{ .Values.tes.gen1BatchImagePublisher }}
            - name: Gen1BatchImageSku
              value: {{ .Values.tes.gen1BatchImageSku }}
            - name: Gen1BatchImageVersion
              value: {{ .Values.tes.gen1BatchImageVersion }}
            - name: BatchPoolRotationForcedDays
              value: {{ .Values.tes.batchPoolRotationForcedDays | quote }}
          image: {{ .Values.tes.image }}
          name: tes
          ports:
            - containerPort: {{ .Values.tes.port }}
          resources:
            requests:
              cpu: "1.5"
              memory: "3072Mi"
            limits:
              cpu: "8.0"
              memory: "8192Mi"
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}-tes-svc
spec:
  ports:
    - name: {{ .Values.tes.port | quote }}
      port: {{ .Values.tes.port }}
      targetPort: {{ .Values.tes.port }}
  selector:
    io.kompose.service: tes
status:
  loadBalancer: {}
