{{ include "terra-batch-libchart.wds-deploy" (list . "coa-helm.wds-deploy") }}
{{ define "coa-helm.wds-deploy" }}
{{ end }}

---

{{ include "terra-batch-libchart.wds-service" (list . "coa-helm.wds-service") }}
{{ define "coa-helm.wds-service" }}
{{ end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-wds-config
data:
  {{ .Values.config.wds.conf_file }}: |-
    spring:
      datasource:
        url: jdbc:mysql://mysqldb/{{ .Values.db.wds.dbname }}
        username: {{ .Values.db.user | quote }}
        password: {{ .Values.db.password | quote }}
      liquibase:
        change-log: classpath:db/changelog.xml
        enabled: true
