exports:
  common:
    cromwell:
      name: coa-cromwell-svc
      image: broadinstitute/cromwell:85-f64b2c4
      port: 8000

    proxy:
      image: nginx:latest
      port: 8000
      type: ClusterIP
      conf_dir: /etc/nginx
      conf_file: nginx.conf
      www_dir: /www/data
      www_file: index.html

    # Note: If you change the location of cbas-ui image config, please also update publish.yml in cbas-ui
    #       repo as the GitHub workflow looks in this file to automatically update the image version
    cbasUI:
      name: cbas-ui
      image: us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.21
      conf_file: config.json
      conf_dir: /usr/share/nginx/html

    # Note: If you change the location of cbas image config, please also update publish.yml in cbas
    #       repo as the GitHub workflow looks in this file to automatically update the image version
    cbas:
      name: cbas
      image: us.gcr.io/broad-dsp-gcr-public/cbas:0.0.58
      conf_dir: /etc/conf
      conf_file: cbas.yaml

    wds:
      name: wds
      image: us.gcr.io/broad-dsp-gcr-public/terra-workspace-data-service:814c536
      conf_dir: /etc/conf
      conf_file: wds.yaml

    postgres:
      image: postgres
      port: 5432
      user: postgres_user
      password: "RUNTIME_PARAMETER"
      wds:
        dbname: wds
      cromwell:
        dbname: cromwell
      cbas:
        dbname: cbas
      startup_dir: /docker-entrypoint-initdb.d
      helper_dir: /wds-helpers
      startup_scripts: # Numbered because scripts in initdb.d are run in alphabetical order
        create_dbs: 01_create_dbs.sh
        seed_wds: 02_seed_wds.sql

    env:
      swaggerBasePath: "SUPPLIED BY LEO"
