cromwell:
  name: coa-cromwell-svc
  image: broadinstitute/cromwell:84-3a19be6-SNAP
  port: 8000

proxy:
  port: 8000
  type: ClusterIP
  conf_dir: /etc/nginx
  conf_file: nginx.conf
  www_dir: /www/data
  www_file: index.html

cbasUI:
  name: cbas-ui
  image: us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.8
  conf_file: config.json
  conf_dir: /usr/share/nginx/html

cbas:
  name: cbas
  image: us.gcr.io/broad-dsp-gcr-public/cbas:0.0.18
  conf_dir: /etc/conf
  conf_file: cbas.yaml

wds:
  name: wds
  image: gcr.io/broad-dsde-dev/workspacedata
  conf_dir: /etc/conf
  conf_file: wds.yaml

postgres:
  port: 5432
  user: postgres_user
  password: "RUNTIME_PARAMETER"
  wds:
    dbname: wds
  cromwell:
    dbname: cromwell
  startup_dir: /docker-entrypoint-initdb.d
  helper_dir: /wds-helpers
  startup_scripts: # Numbered because scripts in initdb.d are run in alphabetical order
    create_dbs: 01_create_dbs.sh
    seed_wds: 02_seed_wds.sql

env:
  swaggerBasePath: "SUPPLIED BY LEO"