apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cbas-config
data:
  {{ .Values.config.file }}: |-
    workflow-engines:
      cromwell:
        baseUri: "http://localhost:8000"
        healthUri: "http://localhost:8000/engine/v1/status"