###########################
# Deployment
###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-depl
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.config.serviceAccount.name }}
      volumes:
        - name: {{ include "app.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc
        - name: {{ include "app.fullname" . }}-cromwell-config
          configMap:
            name: {{ include "app.fullname" . }}-cromwell-config
            items:
              - key: {{ .Values.config.file }}
                path: {{ .Values.config.file }}
      containers:
        - name: {{ .Chart.Name }}-container
          # Keep this format stable for automatic version bumps from https://github.com/broadinstitute/cromwell/pull/6739
          image: broadinstitute/cromwell:79-69b85e0-SNAP
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: {{ include "app.fullname" . }}-cromwell-config
              mountPath: {{ .Values.config.dir }}/{{ .Values.config.file }}
              subPath: {{ .Values.config.file }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ include "dbPassword" . | b64enc | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_SERVICE
              value: {{ include "app.fullname" . }}-postgres
            - name: POSTGRES_PORT
              value: "{{ .Values.db.port }}"
            - name: SWAGGER_BASE_PATH
              value: "{{ .Values.env.swaggerBasePath }}"
          command:
            - "bin/bash"
            - "-c"
            - >-
             java
             -Ddatabase.profile=slick.jdbc.PostgresProfile$
             -Ddatabase.db.driver=org.postgresql.Driver
             -Ddatabase.db.url=jdbc:postgresql://$POSTGRES_SERVICE:$POSTGRES_PORT/$POSTGRES_DB
             -Ddatabase.db.user=$POSTGRES_USER
             -Ddatabase.db.password=$POSTGRES_PASSWORD
             -Ddatabase.db.port=$POSTGRES_PORT
             -Ddatabase.db.connectionTimeout=5000
             -Dconfig.file={{ .Values.config.dir }}/{{ .Values.config.file }}
             -jar /app/cromwell.jar
             server
