apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-cromwell-svc
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "app.cromwell.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
