{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cromwell-pv
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.hostPath }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
  {{- end }}
  claimRef:
    namespace: {{ $.Release.Namespace }}
    name: cromwell-pvc
  {{- if .Values.persistence.gcePersistentDisk }}
  gcePersistentDisk:
    pdName: {{ .Values.persistence.gcePersistentDisk }}
    fsType: ext4
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cromwell-pvc
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  volumeName: cromwell-pv
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- end }}
