###########################
# Deployment
###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: {{ include "dbPassword" . | b64enc | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
---
###########################
# Cluster IP Service
###########################
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
