{{- include "cromwell-common.reverse-proxy-deploy" (list . "cromwell-helm.reverse-proxy-deploy") -}}
{{- define "cromwell-helm.reverse-proxy-deploy" -}}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.config.serviceAccount.name }}
{{- end -}}