name: automerge
on:
  workflow_run:
    workflows:
      - Check Helm templates
      - jenkins-simulator
    types:
      - completed
jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
    - name: dump-github-context
      run: |
        echo '${{ toJSON(github) }}'
        echo $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
        jq $GITHUB_EVENT_PATH
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    # if: github.event.label.name == 'automerge' && github.event.sender.login == 'broadbot'
    steps:
      - name: auto-approve-step
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
  automerge:
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
      - name: automerge
        uses: "broadinstitute/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_FORKS: false
          MERGE_RETRIES: 72 # Retry for 6 minutes instead of 30s
          MERGE_RETRY_SLEEP: 5000 # 5 seconds
          UPDATE_METHOD: rebase
          UPDATE_RETRIES: 72 # Retry updates for 6 minutes instead of once
          UPDATE_RETRY_SLEEP: 5000 # 5 seconds
          MERGE_REQUIRED_APPROVALS: 0
