name: label-with-broadbot

on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: string
        description: PR number to label

jobs:
  label-with-broadbot:
    name: label-with-broadbot
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BROADBOT_TOKEN }}
          script: |
            const label_response = github.rest.issues.addLabels({
              owner: 'broadinstitute',
              repo: 'cromwhelm',
              issue_number: ${{ inputs.pr_number }},
              labels: ['automerge']
            });

