name: Check Helm templates

on:
  workflow_dispatch:
  # push:

jobs:
  run-helm-template:
    name: Create Leonardo PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: Update dependencies
        run: |
          helm dependency update cromwell-helm/
          helm dependency update coa-helm/
      - name: Check template values
        run: |
          helm template cromwell-helm/
          helm template coa-helm/
