name: Make Leonardo PR

on:
  workflow_run:
    workflows: [update-and-publish-cromwell-helm-chart]
    types: [completed]
  workflow_dispatch:

jobs:
  make-leonardo-pr:
    name: Create Leonardo PR
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the cromwhelm repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work

      - name: Find out latest chart version from cromwhelm repository
        run: |
          function getLatestChartVersion(){
            ls $1 | \
            grep ^cromwell- | \
            sed 's:cromwell-::; s:.tgz::' | \
            sort -V | \
            tail -1
          }

          echo "NEW_CROMWELL_HELM_V=$(getLatestChartVersion charts)" >> $GITHUB_ENV

      - name: Clone leonardo
        uses: actions/checkout@v2
        with:
          repository: broadinstitute/leonardo
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
          path: leonardo
      - name: Update & push to leonardo
        id: update-and-push
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          function getVersionFromReference(){
            cat $1 | \
            sed -e '/cromwellApp/,/chartVersion/!d' -e 's:^[ ]*::' | \
            tail -1 | \
            awk -F'"' '{print $2}'
          }

          function getVersionFromDocker(){
            grep "ENV CROMWELL_CHART_VERSION" $1 | awk -F'[ ]' '{ print $3 }'
          }

          cd leonardo

          versionFromReference=$(getVersionFromReference http/src/main/resources/reference.conf)
          versionFromDocker=$(getVersionFromDocker Dockerfile)

          if [ $versionFromReference != $versionFromDocker ]; then
            echo "ERROR: Cromwell versions in reference.conf and Dockerfile do not match." \
                 "($versionFromReference != $versionFromDocker)" \
            exit 1
          fi

          echo "OLD_CROMWELL_HELM_V=$versionFromReference" >> $GITHUB_ENV


          NEW_BRANCH_NAME="cromwell_helm_${NEW_CROMWELL_HELM_V}-AUTOMERGE"
          TEMP=$(mktemp)
          git checkout -b "${NEW_BRANCH_NAME}"

          SED_STRING="s/${versionFromReference}/${NEW_CROMWELL_HELM_V}/g"
          FILES=( "Dockerfile" "http/src/main/resources/reference.conf" )
          for i in "${FILES[@]}"
          do
            echo "Updating ${i}"
            sed "${SED_STRING}" ${i} > ${TEMP}
            mv ${TEMP} ${i}
            git add ${i}
          done

          echo "Pushing to leonardo branch ${NEW_BRANCH_NAME}"
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -m "Auto-update Cromwell version to ${NEW_CROMWELL_HELM_V}"
          git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/leonardo.git ${NEW_BRANCH_NAME}
          echo ::set-output name=NEW_BRANCH_NAME::${NEW_BRANCH_NAME}
      - name: Create leonardo PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BROADBOT_TOKEN }}
          script: |
            const result = await github.rest.pulls.create({
              title: '[AUTOMERGE] Update Cromwell version to ${NEW_CROMWELL_HELM_V}',
              owner: 'broadinstitute',
              repo: 'leonardo',
              head: '${{ steps.update-and-push.outputs.NEW_BRANCH_NAME }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[Cromwhelm actions/make_leo_pr](https://github.com/broadinstitute/cromwhelm/blob/main/.github/workflows/make_leo_pr.yml), using',
                '[github actions/github-script](https://github.com/actions/github-script).',
                '',
                'It updates cromwell-helm from version ${OLD_CROMWELL_HELM_V} to ${NEW_CROMWELL_HELM_V}.'
              ].join('\n')
            });

