name: Make Leonardo PR

on:
  workflow_dispatch:
    inputs:
      old_cromwell_helm_version:
        description: 'What version of cromwell-helm to update from'
        required: true
      new_cromwell_helm_version:
        description: 'What version of cromwell-helm to update to'
        required: true
      jira_ticket:
        description: 'The JIRA ticket to link the update PR to'
        required: true

jobs:
  make-leonardo-pr:
    name: Create Leonardo PR
    runs-on: ubuntu-latest
    steps:
      - name: Clone leonardo
        uses: actions/checkout@v2
        with:
          repository: broadinstitute/leonardo
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
          path: leonardo
      - name: Update & push to leonardo
        id: update-and-push
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          cd leonardo
          JIRA_TICKET=${{ github.event.inputs.jira_ticket }}
          OLD_CROMWELL_HELM_V=${{ github.event.inputs.old_cromwell_helm_version }}
          NEW_CROMWELL_HELM_V=${{ github.event.inputs.new_cromwell_helm_version }}
          NEW_BRANCH_NAME="${JIRA_TICKET}_cromwell_helm_${NEW_CROMWELL_HELM_V}"
          TEMP=$(mktemp)
          git checkout -b "${NEW_BRANCH_NAME}"
          SED_STRING="s/${OLD_CROMWELL_HELM_V}/${NEW_CROMWELL_HELM_V}/g"
          FILES=( "Dockerfile" "http/src/main/resources/reference.conf" )
          for i in "${FILES[@]}"
          do
            echo "Updating ${i}"
            sed "${SED_STRING}" ${i} > ${TEMP}
            mv ${TEMP} ${i}
            git add ${i}
          done
          echo "Pushing to leonardo branch ${NEW_BRANCH_NAME}"
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -m "Updating Cromwell version to ${NEW_CROMWELL_HELM_V}"
          git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/leonardo.git ${NEW_BRANCH_NAME}
          echo ::set-output name=NEW_BRANCH_NAME::${NEW_BRANCH_NAME}
      - name: Create leonardo PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BROADBOT_TOKEN }}
          script: |
            const result = await github.rest.pulls.create({
              title: '${{ github.event.inputs.jira_ticket }}: Update Cromwell version to ${{ github.event.inputs.new_cromwell_helm_version }}',
              owner: 'broadinstitute',
              repo: 'leonardo',
              head: '${{ steps.update-and-push.outputs.NEW_BRANCH_NAME }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[Cromwell actions/make_publish_prs](https://github.com/broadinstitute/cromwell/blob/develop/.github/workflows/make_publish_prs.yml), using',
                '[github actions/github-script](https://github.com/actions/github-script).',
                '',
                'It updates cromwell from version ${{ github.event.inputs.old_cromwell_helm_version }} to ${{ github.event.inputs.new_cromwell_helm_version }}.'
              ].join('\n')
            });

