name: update-and-publish-cromwell-helm-chart
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  update-and-publish:
    if: ( !startsWith(github.event.head_commit.message, 'Auto update cromwell-helm chart version') )
    name: Update and publish new cromwell-helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work

      - name: Find out next chart version
        run: |
          currentVersionGCP=$(grep '^version:' cromwell-helm/Chart.yaml | awk '{print $NF}')
          currentVersionCOA=$(grep '^version:' coa-helm/Chart.yaml | awk '{print $NF}')

          # this will increment only the patch version digit. For example, it will update 0.1.10 => 0.1.11
          nextVersionGCP=$(echo ${currentVersionGCP} | awk -F. -v OFS=. '{$NF += 1 ; print}')
          nextVersionCOA=$(echo ${currentVersionGCP} | awk -F. -v OFS=. '{$NF += 1 ; print}')

          echo "CURRENT_VERSION_GCP=$currentVersionGCP" >> $GITHUB_ENV
          echo "NEXT_VERSION_GCP=$nextVersionGCP" >> $GITHUB_ENV

          echo "CURRENT_VERSION_COA=$currentVersionCOA" >> $GITHUB_ENV
          echo "NEXT_VERSION_COA=$nextVersionCOA" >> $GITHUB_ENV

      - name: Bump chart version
        run: |
          sed -i "s/$CURRENT_VERSION_GCP/$NEXT_VERSION_GCP/" cromwell-helm/Chart.yaml
          sed -i "s/$CURRENT_VERSION_COA/$NEXT_VERSION_COA/" coa-helm/Chart.yaml

      - name: Publish the new helm chart and update index.yaml
        run: |
          helm dependency update cromwell-helm/
          helm package cromwell-helm/
          mv cromwell-${NEXT_VERSION_GCP}.tgz charts/cromwell-${NEXT_VERSION_GCP}.tgz
          helm repo index --url https://broadinstitute.github.io/cromwhelm/charts/ charts

      - name: Push changes to GitHub
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          git fetch
          git checkout main
          git diff
          git add .
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -am "Auto update cromwell-helm chart version to $NEXT_VERSION_GCP and coa-helm chart version to $NEXT_VERSION_COA"
          git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/cromwhelm.git main
