name: update-and-publish-cromwell-helm-chart
on: [pull_request]
#  pull_request:
#    types:
#      - closed

jobs:
  update-and-publish:
    name: Updates and publishes new cromwell-helm chart
    # only run this action when a PR is merged (and not on "closed")
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Find out next chart version
        run: |
          currentVersion=$(grep 'version:' cromwell-helm/Chart.yaml | awk '{print $NF}')

          # this will increment only the last version digit. For example, it will update 0.1.10 => 0.1.11
          nextVersion=$(echo ${currentVersion} | awk -F. -v OFS=. '{$NF += 1 ; print}')

          echo "CURRENT_VERSION=$currentVersion" >> $GITHUB_ENV
          echo "NEXT_VERSION=$nextVersion" >> $GITHUB_ENV

      - name: Update chart.yaml file with new chart version
        run: |
          sed -i "s/$CURRENT_VERSION/$NEXT_VERSION/" cromwell-helm/Chart.yaml

      - name: Publish the new chart
        run: |
          helm package cromwell-helm/
          mv cromwell-${NEXT_VERSION}.tgz charts/cromwell-${NEXT_VERSION}.tgz
          helm repo index --url https://broadinstitute.github.io/cromwhelm/charts/ charts

      - name: Push changes to GitHub
        env:
          BROADBOT_GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
        run: |
          git diff
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -am "Auto update to cromwell-helm chart version to $NEXT_VERSION"
          git push https://broadbot:$BROADBOT_GITHUB_TOKEN@github.com/broadinstitute/cromwhelm.git ss_auto_update_chart_version

