# Default values for cromwell-local.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  postgres:
    repository: postgres
    pullPolicy: Always
    tag: latest
    env:
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
  cromwell:
    repository: broadinstitute/cromwell
    pullPolicy: Always
    tag: 66-5f8a277
    command:
      - "bin/bash"
      - "-c"
      - >-
        java
        -jar /app/cromwell.jar
        server

#        -Ddatabase.profile=slick.jdbc.PostgresProfile$
#        -Ddatabase.db.driver=org.postgresql.Driver
#        -Ddatabase.db.url=jdbc:postgresql://postgres-service:5432/cromwell
#        -Ddatabase.db.user=postgres
#        -Ddatabase.db.password=mysecretpassword
#        -Ddatabase.db.port=5432
#        -Ddatabase.db.connectionTimeout=5000

imagePullSecrets: []
nameOverride: "cromwell-local-app"
fullnameOverride: "cromwell-local-chart"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  cromwell:
    type: NodePort
    port: 8000
  postgres:
    type: ClusterIP
    port: 5432

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
