name: cromwell-on-azure
description: A cromwell deployment designed to run on Azure with Postgres. 
version: 0.2.390
apiVersion: v2
dependencies:
  - name: terra-batch-libchart
    version: 0.0.2
    repository: file://../terra-batch-libchart
    import-values:
      - common
