# This is a template.
# Don't change this file; copy it instead, and fill in the values needed for deployment.
# Obtain these values from someone on the development team.
 
config:
  resourceGroup: "UNDEFINED"
  azureServicesAuthConnectionString: "UNDEFINED"
  applicationInsightsAccountName: "UNDEFINED"
  cosmosDbAccountName: "UNDEFINED"
  batchAccountName: "UNDEFINED"
  batchNodesSubnetId: "UNDEFINED"
  relayListenerSamResourceId: "UNDEFINED"
  relayListenerConnectionString: "UNDEFINED"
  relayListenerEndpoint: "UNDEFINED"
  relayListenerConnectionName: "UNDEFINED"
  relayListenerSamUrl: "UNDEFINED"

db:
  name: UNDEFINED
  port: 3306
  user: UNDEFINED
  password: UNDEFINED

persistence:
  storageResourceGroup: "UNDEFINED"
  storageAccount: "UNDEFINED"

fullnameOverride: "coa"
