# This is a template.
# Don't change this file; copy it instead, and fill in the values needed for deployment.
# Obtain these values from someone on the development team.
 
config:
  resourceGroup: "UNDEFINED"
  azureServicesAuthConnectionString: "UNDEFINED"
  applicationInsightsAccountName: "UNDEFINED"
  cosmosDbAccountName: "UNDEFINED"
  batchAccountName: "UNDEFINED"
  batchNodesSubnetId: "UNDEFINED"
  drsUrl: "UNDEFINED"

relay:
  path: RUNTIME_PARAMETER

persistence:
  storageResourceGroup: "UNDEFINED"
  storageAccount: "UNDEFINED"
  blobContainer: "UNDEFINED"
  leoAppInstanceName: "UNDEFINED"

fullnameOverride: "coa"
