config:
  resourceGroup: RUNTIME_PARAMETER
  azureServicesAuthConnectionString: RUNTIME_PARAMETER
  applicationInsightsAccountName: RUNTIME_PARAMETER
  cosmosDbAccountName: RUNTIME_PARAMETER
  batchAccountName: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  azureOfferDurableId: MS-AZR-0003p
  blobxferImageName: ""
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false

tes: 
  image: mcr.microsoft.com/cromwellonazure/tes:2
  port: 80

triggerservice: 
  image: mcr.microsoft.com/cromwellonazure/triggerservice:2

relaylistener:
  image: terradevacrpublic.azurecr.io/terra-azure-relay-listeners:9eb4762
  port: 8080
  connectionString: RUNTIME_PARAMETER
  connectionName: RUNTIME_PARAMETER
  targetHost: "http://coa-reverse-proxy-service:8000/"
  endpoint: RUNTIME_PARAMETER
  samResourceId: RUNTIME_PARAMETER
  samResourceType: "workspace"
  samUrl: RUNTIME_PARAMETER

proxy:
  port: 8000
  type: ClusterIP
  conf_dir: /etc/nginx
  conf_file: nginx.conf
  www_dir: /www/data
  www_file: index.html

persistence:
  blobPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  storageResourceGroup: RUNTIME_PARAMETER
  storageAccount: RUNTIME_PARAMETER
  blobContainers:
    - configuration
    - cromwell-executions
    - cromwell-workflow-logs
    - inputs
    - outputs
    - workflows

postgres:
  port: 5432
  user: postgres_user
  password: "RUNTIME_PARAMETER"
  wds:
    dbname: wds
  cromwell:
    dbname: cromwell
  startup_dir: /docker-entrypoint-initdb.d
  helper_dir: /wds-helpers
  startup_scripts: # Numbered because scripts in initdb.d are run in alphabetical order
    create_dbs: 01_create_dbs.sh
    seed_wds: 02_seed_wds.sql

cromwell:
  name: coa-cromwell-svc
  image: broadinstitute/cromwell:84-3a19be6-SNAP
  port: 8000

cbasUI:
  name: cbas-ui
  image: us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.9
  conf_file: config.json
  conf_dir: /usr/share/nginx/html

cbas:
  name: cbas
  image: us.gcr.io/broad-dsp-gcr-public/cbas:0.0.19
  conf_dir: /etc/conf
  conf_file: cbas.yaml

wds:
  name: wds
  image: gcr.io/broad-dsde-dev/workspacedata
  conf_dir: /etc/conf
  conf_file: wds.yaml

env:
  swaggerBasePath: "SUPPLIED BY LEO"

