config:
  resourceGroup: RUNTIME_PARAMETER
  landingZoneId: RUNTIME_PARAMETER
  subscriptionId: RUNTIME_PARAMETER
  region: RUNTIME_PARAMETER
  applicationInsightsAccountKey: RUNTIME_PARAMETER
  batchAccountName: RUNTIME_PARAMETER
  batchAccountKey: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  drsUrl: RUNTIME_PARAMETER
  workflowExecutionIdentity: RUNTIME_PARAMETER

tes: 
  # Test image, should be replaced with an official release when available
  image: mcr.microsoft.com/cromwellonazure/tes:int-4.0.23039.6675
  port: 80
  # One of Trace, Debug, Information, Warning, Error, Critical, None
  logLevel: Warning
  sasTokenExpirationInSeconds: 86400
  retryPolicyOptions:
    maxRetryCount: 5
    exponentialBackOffExponent: 2
  containerRegistry:
    autoDiscoveryEnabled: false
    registryInfoCacheExpirationInHour: 1
  allowedHosts: "*"
  batchImagePublisher: "microsoft-dsvm"
  batchImageOffer: "ubuntu-hpc"
  batchImageSku: "2004"
  batchImageVersion: "latest"
  batchNodeAgentSkuId: "batch.node.ubuntu 20.04"
  gen2BatchNodeAgentSkuId: "batch.node.ubuntu 20.04"
  gen2BatchImageOffer: "ubuntu-hpc"
  gen2BatchImagePublisher: "microsoft-dsvm"
  gen2BatchImageSku: "2004"
  gen2BatchImageVersion: "latest"
  gen1BatchImageOffer: "ubuntu-server-container"
  gen1BatchImagePublisher: "microsoft-azure-batch"
  gen1BatchImageSku: "20-04-lts"
  gen1BatchImageVersion: "latest"
  batchPoolRotationForcedDays: 7
  azureOfferDurableId: MS-AZR-0003p
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false

relay:
  path: RUNTIME_PARAMETER

persistence:
  postgresPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  storageAccount: RUNTIME_PARAMETER
  blobContainer: RUNTIME_PARAMETER
  leoAppInstanceName: RUNTIME_PARAMETER
  workspaceManager:
    url: RUNTIME_PARAMETER
    workspaceId: RUNTIME_PARAMETER
    containerResourceId: RUNTIME_PARAMETER

identity:
  name: RUNTIME_PARAMETER
  resourceId: RUNTIME_PARAMETER
  clientId: RUNTIME_PARAMETER
