service:
  tesPort: 80
  cromwellPort: 8000
  relayListenerPort: 80

config:
  resourceGroup: RUNTIME_PARAMETER
  azureServicesAuthConnectionString: RUNTIME_PARAMETER
  applicationInsightsAccountName: RUNTIME_PARAMETER
  cosmosDbAccountName: RUNTIME_PARAMETER
  azureOfferDurableId: MS-AZR-0003p
  batchAccountName: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  blobxferImageName: ""
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false
  relayListenerConnectionString: RUNTIME_PARAMETER
  relayListenerConnectionName: RUNTIME_PARAMETER
#  relayListenerSamResourceId:
#  relayListenerSamUrl:
  relayListenerTargetHost: "http://cromwell:8000/"

images:
  mysql: mysql:latest
  cromwell: broadinstitute/cromwell:79
  tes: mcr.microsoft.com/cromwellonazure/tes:2
  triggerservice: mcr.microsoft.com/cromwellonazure/triggerservice:2
  relaylistener: terradevacrpublic.azurecr.io/terra-azure-relay-listeners:b26c311

containers:
  - configuration
  - cromwell-executions
  - cromwell-workflow-logs
  - inputs
  - outputs
  - workflows

persistence:
  blobPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  mysqlSize: 32Gi
  storageResourceGroup: RUNTIME_PARAMETER
  storageAccount: RUNTIME_PARAMETER

db:
  name: cromwell_db
  port: 3306
  user: cromwell
  password: cromwell
