config:
  resourceGroup: RUNTIME_PARAMETER
  azureServicesAuthConnectionString: RUNTIME_PARAMETER
  applicationInsightsAccountName: RUNTIME_PARAMETER
  cosmosDbAccountName: RUNTIME_PARAMETER
  batchAccountName: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  azureOfferDurableId: MS-AZR-0003p
  blobxferImageName: ""
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false
  drsUrl: RUNTIME_PARAMETER
  workflowExecutionIdentity: RUNTIME_PARAMETER

tes: 
  image: mcr.microsoft.com/cromwellonazure/tes:3.1
  port: 80

relay:
  path: RUNTIME_PARAMETER

persistence:
  postgresPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  storageAccount: RUNTIME_PARAMETER
  blobContainer: RUNTIME_PARAMETER
  leoAppInstanceName: RUNTIME_PARAMETER
  workspaceManager:
    url: RUNTIME_PARAMETER
    workspaceId: RUNTIME_PARAMETER
    containerResourceId: RUNTIME_PARAMETER

identity:
  name: RUNTIME_PARAMETER
  resourceId: RUNTIME_PARAMETER
  clientId: RUNTIME_PARAMETER
