service:
  tesPort: 80
  cromwellPort: 8000
  relayListenerPort: 80

config:
  resourceGroup: RUNTIME_PARAMETER
  azureServicesAuthConnectionString: RUNTIME_PARAMETER
  applicationInsightsAccountName: RUNTIME_PARAMETER
  cosmosDbAccountName: RUNTIME_PARAMETER
  azureOfferDurableId: MS-AZR-0003p
  batchAccountName: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  blobxferImageName: ""
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false
  relayListenerConnectionString: RUNTIME_PARAMETER
  relayListenerConnectionName: RUNTIME_PARAMETER
  relayListenerSamResourceId: RUNTIME_PARAMETER
  relayListenerSamResourceType: "workspace"
  relayListenerSamUrl: RUNTIME_PARAMETER
  relayListenerTargetHost: "http://coa-proxy-svc:8000/"

images:
  mysql: mysql:latest
  cromwell: broadinstitute/cromwell:79
  tes: mcr.microsoft.com/cromwellonazure/tes:2
  triggerservice: mcr.microsoft.com/cromwellonazure/triggerservice:2
  relaylistener: terradevacrpublic.azurecr.io/terra-azure-relay-listeners:9eb4762

containers:
  - configuration
  - cromwell-executions
  - cromwell-workflow-logs
  - inputs
  - outputs
  - workflows

persistence:
  blobPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  mysqlSize: 32Gi
  storageResourceGroup: RUNTIME_PARAMETER
  storageAccount: RUNTIME_PARAMETER

db:
  name: cromwell_db
  port: 3306
  user: cromwell
  password: cromwell

### Transferred values from original GCP/Leo implementation:
proxyService:
  type: ClusterIP
  port: 8000

config:
  serviceAccount:
    name: "SUPPLIED BY LEO"
    annotations:
      gcpServiceAccount: "SUPPLIED BY LEO"
  proxy:
    conf_dir: /etc/nginx
    conf_file: nginx.conf
    www_dir: /www/data
    www_file: index.html
  cbas:
    conf_dir: /etc/conf
    conf_file: cbas.yaml
  cbasUI:
    conf_file: config.json
    conf_dir: /usr/share/nginx/html

cbas:
  name: cbas

batchAnalysisUI:
  name: batch-analysis-ui

# These commented values are left intact from the GCP/Leo version of this chart,
#   because I think they will be useful reminders when we integrate that chart with this one.
ingress:
  # enabled: true
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/proxy-redirect-from: "SUPPLIED BY LEO"
    # nginx.ingress.kubernetes.io/proxy-redirect-to: "SUPPLIED BY LEO"
    # nginx.ingress.kubernetes.io/rewrite-target: "SUPPLIED BY LEO"
    # nginx.ingress.kubernetes.io/auth-tls-secret: "SUPPLIED BY LEO"
  path: "https://terra-coa.servicebus.windows.net/terra-coa-cromwellapp/"
  # hosts:
  #   - host: "SUPPLIED BY LEO"
  #     paths:
  #       - "SUPPLIED BY LEO"
  # tls:
  #   - secretName: "SUPPLIED BY LEO"
  #     hosts:
  #       - "SUPPLIED BY LEO"

