config:
  resourceGroup: RUNTIME_PARAMETER
  landingZoneId: RUNTIME_PARAMETER
  subscriptionId: RUNTIME_PARAMETER
  region: RUNTIME_PARAMETER
  applicationInsightsConnectionString: RUNTIME_PARAMETER
  batchAccountName: RUNTIME_PARAMETER
  batchAccountKey: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  drsUrl: RUNTIME_PARAMETER

provenance:
  sourceWorkspaceId: ""
  userAccessToken: RUNTIME_PARAMETER

fullnameOverride: RUNTIME_PARAMETER

cromwell:
  apiVersion: "v1"
tes:
  apiVersion: "v1"
  image: mcr.microsoft.com/ga4gh/tes:4.4.23225.8067
  port: 80
  # One of Trace, Debug, Information, Warning, Error, Critical, None
  logLevel: Warning
  # Currently this represents the max task processing time
  sasTokenExpirationInSeconds: 86400
  allowedHosts: "*"
  azureOfferDurableId: MS-AZR-0003p
  retryPolicy:
    maxRetryCount: 5
    exponentialBackOffExponent: 2
  containerRegistry:
    autoDiscoveryEnabled: false
    registryInfoCacheExpirationInHour: 1
  batchImageGen1:
    nodeAgentSkuId: "batch.node.ubuntu 20.04"
    offer: "ubuntu-server-container"
    publisher: "microsoft-azure-batch"
    sku: "20-04-lts"
    version: "latest"
  batchImageGen2:
    nodeAgentSkuId: "batch.node.ubuntu 20.04"
    offer: "ubuntu-hpc"
    publisher: "microsoft-dsvm"
    sku: "2004"
    version: "latest"
  batchNodes:
    disablePublicIpAddress: false
  batchScheduling:
    disable: false
    poolRotationForcedDays: 7
    usePreemptibleVmsOnly: false

relay:
  path: RUNTIME_PARAMETER

persistence:
  postgresPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  storageAccount: RUNTIME_PARAMETER
  blobContainer: RUNTIME_PARAMETER
  leoAppInstanceName: RUNTIME_PARAMETER
  workspaceManager:
    url: RUNTIME_PARAMETER
    workspaceId: RUNTIME_PARAMETER
    containerResourceId: RUNTIME_PARAMETER

identity:
  name: RUNTIME_PARAMETER
  resourceId: RUNTIME_PARAMETER
  clientId: RUNTIME_PARAMETER

workloadIdentity:
  enabled: false
  serviceAccountName: RUNTIME_PARAMETER

postgres:
  podLocalDatabaseEnabled: true
  podLocalDatabaseEnabledForTES: true
  pgbouncer:
    enabled: false
    port: 6432
