service:
  tesPort: 80
  cromwellPort: 8000
  relayListenerPort: 80
  # proxyService
  type: ClusterIP
  port: 8000

config:
  resourceGroup: RUNTIME_PARAMETER
  azureServicesAuthConnectionString: RUNTIME_PARAMETER
  applicationInsightsAccountName: RUNTIME_PARAMETER
  cosmosDbAccountName: RUNTIME_PARAMETER
  azureOfferDurableId: MS-AZR-0003p
  batchAccountName: RUNTIME_PARAMETER
  batchNodesSubnetId: RUNTIME_PARAMETER
  blobxferImageName: ""
  disableBatchNodesPublicIpAddress: false
  disableBatchScheduling: false
  dockerInDockerImageName: ""
  usePreemptibleVmsOnly: false
  relayListenerConnectionString: RUNTIME_PARAMETER
  relayListenerEndpoint: RUNTIME_PARAMETER
  relayListenerConnectionName: RUNTIME_PARAMETER
  relayListenerSamResourceId: RUNTIME_PARAMETER
  relayListenerSamResourceType: "workspace"
  relayListenerSamUrl: RUNTIME_PARAMETER
  relayListenerTargetHost: "http://coa-reverse-proxy-service:8000/"
  proxy:
    conf_dir: /etc/nginx
    conf_file: nginx.conf
    www_dir: /www/data
    www_file: index.html
  cbas:
    conf_dir: /etc/conf
    conf_file: cbas.yaml
  cbasUI:
    conf_file: config.json
    conf_dir: /usr/share/nginx/html
  wds:
    conf_dir: /etc/conf
    conf_file: wds.yaml
  postgres:
    startup_dir: /docker-entrypoint-initdb.d
    helper_dir: /wds-helpers
    startup_scripts:
      # Numbered because scripts in initdb.d are run in alphabetical order:
      create_dbs: 01_create_dbs.sh
      seed_wds: 02_seed_wds.sql

images:
  cromwell: broadinstitute/cromwell:84-3a19be6-SNAP
  tes: mcr.microsoft.com/cromwellonazure/tes:2
  triggerservice: mcr.microsoft.com/cromwellonazure/triggerservice:2
  relaylistener: terradevacrpublic.azurecr.io/terra-azure-relay-listeners:9eb4762

containers:
  - configuration
  - cromwell-executions
  - cromwell-workflow-logs
  - inputs
  - outputs
  - workflows

persistence:
  blobPvcSize: 10Gi
  cromwellTmpSize: 32Gi
  storageResourceGroup: RUNTIME_PARAMETER
  storageAccount: RUNTIME_PARAMETER

postgres:
  port: 5432
  user: postgres_user
  password: "RUNTIME_PARAMETER"
  wds:
    dbname: wds
  cromwell:
    dbname: cromwell

cromwell:
  name: coa-cromwell-svc

cbasUI:
  name: cbas-ui
  image: us.gcr.io/broad-dsp-gcr-public/cbas-ui:0.0.8

cbas:
  name: cbas
  image: us.gcr.io/broad-dsp-gcr-public/cbas:0.0.18

wds:
  name: wds
  image: gcr.io/broad-dsde-dev/workspacedata

env:
  swaggerBasePath: "SUPPLIED BY LEO"